import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";
import Navbar from "@/components/navbar/Navbar";
import WrapperContainer from "@/components/WrapperContainer";
import { Analytics } from "@vercel/analytics/react";

const OpenSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code With Credo",
  description: "Generated by create next app",
  keywords: [
    "Frontend",
    "Developer",
    "Frontend Developer",
    "Szakacs Tamas",
    "web application",
    "website",
    "next.js developer",
    "react developer",
  ],
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={OpenSans.className}>
        <ThemeProvider defaultTheme="dark" attribute="class" enableSystem>
          <Navbar />
          <WrapperContainer>{children}</WrapperContainer>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
